(rule
 (targets unitcon)
 (deps
  ../src/main.exe
  (source_tree ../deps))
 (action
  (progn
   (system "cp -r ../deps ./deps")
   (system "ln -sf ../src/main.exe ./unitcon"))))

(rule
 (alias runtest)
 (deps
  unitcon
  (source_tree simple))
 (targets simple.output)
 (action
  (progn
   (run
    ./unitcon
    run
    simple
    --target
    Main.java:11
    --batch-size
    1
    --out-dir
    unitcon-simple
    --ignore-time)
   (with-stdout-to
    %{targets}
    (run cat unitcon-simple/unitcon-tests/UnitconTest1.java)))))

(rule
 (alias runtest)
 (action
  (diff simple.expected simple.output)))

(rule
 (alias runtest)
 (deps
  unitcon
  (source_tree dup))
 (targets dup.output)
 (action
  (progn
   (run
    ./unitcon
    run
    dup
    --target
    Main.java:4
    --batch-size
    1
    --out-dir
    unitcon-dup
    --ignore-time)
   (with-stdout-to
    %{targets}
    (run cat unitcon-dup/unitcon-tests/UnitconTest1.java)))))

(rule
 (alias runtest)
 (action
  (diff dup.expected dup.output)))

(test
 (name unit)
 (libraries unitconLib oUnit))
