(rule
 (targets unitcon)
 (deps
  ../../src/main.exe
  (source_tree ../../deps))
 (action
  (progn
   (system "cp -r ../../deps ./deps")
   (system "ln -sf ../../src/main.exe ./unitcon"))))

(rule
 (alias runtest)
 (deps
  unitcon
  (source_tree example))
 (targets example.output)
 (action
  (progn
   (run
    ./unitcon
    run
    example
    --target
    src/main/java/example/Checker.java:25
    --batch-size
    1
    --out-dir
    unitcon-example
    --ignore-time)
   (with-stdout-to
    %{targets}
    (run cat unitcon-example/unitcon-tests/UnitconTest1.java)))))

(rule
 (alias runtest)
 (action
  (diff example.expected example.output)))
