name: check

on: [push, pull_request]

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    permissions:
      statuses: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACTION_TOKEN }} 

      - name: Set up JAVA
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.4.14.0+options,ocaml-option-flambda

      - name: Use cached dependencies
        id: cache-opam
        uses: actions/cache@v4
        env:
          cache-name: cache-opam
        with:
          path: |
            ~/.opam
            ./_opam
          key: ${{ env.cache-name }}-build-${{ hashFiles('setup.sh') }}
          restore-keys: |
            ${{ env.cache-name }}-build-${{ hashFiles('setup.sh') }}
            ${{ env.cache-name }}-build-

      - name: Install ocamlformat
        run: opam install ocamlformat.0.26.1

      - name: Check format
        run: |
          eval $(opam env)
          make fmt

      - name: Build
        run: |
          ./setup.sh || { eval $(opam env) && make -j; }

      - name: Run test (regression)
        run: |
          eval $(opam env) && make coverage
