name: check

on: [push, pull_request]

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    permissions:
      statuses: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1.0

      - name: Use cached dependencies
        id: cache-opam
        uses: actions/cache@v4
        env:
          cache-name: cache-opam
        with:
          path: |
            ~/.opam
            ./_opam
          key: ${{ env.cache-name }}-build-${{ hashFiles('setup.sh') }}
          restore-keys: |
            ${{ env.cache-name }}-build-${{ hashFiles('setup.sh') }}
            ${{ env.cache-name }}-build-

      - name: Install ocamlformat
        run: opam install ocamlformat.0.24.1

      - name: Check format
        run: |
          eval $(opam env)
          make fmt

      - name: Build
        run: |
          ./setup.sh || eval $(opam env) && make -j

      - name: Run test (regression)
        run: |
          eval $(opam env) && make coverage > coverage.txt

      - name: Report check status
        run: |
          COVERAGE=`tail -1 coverage.txt | cut -d ' ' -f3`
          echo $COVERAGE
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"","description":"'"${COVERAGE}"'","context":"check/coverage"}'
